name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y -qq pkg-config libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - name: build
      run: cargo build --verbose
    - name: test
      run: cargo test --verbose
    - name: publish to crates.io
      uses: katyo/publish-crates@v1
